### ISSUE TITLE
Need help. 

### ISSUE THREAD

**Issue by TastyCookies124** [aeolingamenfel/discord-text-adventure-bot#13]
So i have everything installed but Idk how to set the bot up please help.

**Comment by aeolingamenfel** [comment]
Do you mean setting up a Discord Bot?

**Comment by aeolingamenfel** [comment]
Sure, here's the steps:

1) Go to [The Developer Pane](https://discordapp.com/developers/docs/intro) for Discord (while you're logged in) and click on "My Apps"
2) Add a new app; this is your bot, name it accordingly
3) in the new app you just created, make sure to upgrade the bot to a "Bot User"
4) Copy and paste the token for the Bot User you just created into the config for my text adventure bot (make sure its in `config.json` not `config.json.example`)
5) Add the bot to whatever servers you want via [these instructions](http://stackoverflow.com/questions/37689289/joining-a-server-with-the-discord-python-api)
6) start your bot up with `node app.js` from the bot directory

And that should be all you need! Let me know if that helps or you have more questions!

**Comment by TastyCookies124** [comment]
![needhelp](https://cloud.githubusercontent.com/assets/25892061/23337674/48e8481e-fbbb-11e6-860a-0dc10d034a9b.png)

well this is what I have so far lol.

**Comment by aeolingamenfel** [comment]
Alright. Did you follow the instructions to install Node/NPM?

**Comment by aeolingamenfel** [comment]
@TastyCookies124 are you still having issues? Can I help?
