### ISSUE TITLE
Can't get bot to work

### ISSUE THREAD

**Issue by Sniperpaul296** [aeolingamenfel/discord-text-adventure-bot#26]
I'm using Ubuntu on windows 10, I followed the instructions, I opened the bash in my folder where the config file is and ran "npm i -g discord-frotz", everything seemed to go fine, (had to use sudo) but where do I find the discort-frotz and how do I run it?

**Comment by aeolingamenfel** [comment]
You have `dfrotz` installed right? If so, you can just run `discord-frotz`. Running that NPM command installed that as a command globally, so as long as you've `cd`'d into the directory with the config file, you should just have to run that command.

**Comment by aeolingamenfel** [comment]
At this point, I haven't heard from you in several months. I'm going to close this issue for now. Please reopen if you are still having an issue.
