### ISSUE TITLE
Bot now works on Windows

### ISSUE THREAD

**Issue by MiltonLibraryAssistant** [aeolingamenfel/discord-text-adventure-bot#28]
Hey, thanks for writing this fun bot! It runs just fine now on Windows 10, so you can remove the disclaimer from the main page. It does require a newer version of discord.io (the solution to https://github.com/izy521/discord.io/issues/234 describes how to install this version), since the current version is broken.

**Comment by aeolingamenfel** [comment]
Thank you for reaching out and informing me! I'll hop into the repo and get that updated!
