### ISSUE TITLE
Messed up formatting on responses.

### ISSUE THREAD

**Issue by JiFish** [aeolingamenfel/discord-text-adventure-bot#5]
Hi! Great bot. I've been looking for something just like this.

I've been getting some screwed up formatting in my responses. I was wondering if this is something fixable.

Some examples:
```
JiFish - Today at 6:09 PM
$look
frotz-botBOT - Today at 6:09 PM
look
1
West of House
You are standing in an open field west of a white house, with a boarded front
oor.
There is a small mailbox here.
>
```

```
JiFish - Today at 6:09 PM
$w
frotz-botBOT - Today at 6:09 PM
w
Forest       5
Forest
This is a forest, with trees in all directions. To the east, there appears to besunlight.
>
```
```
$take
frotz-botBOT - Today at 6:11 PM
take
dWhat do you want to take?
>
```

Other the the obvious issues, I'm not sure if repeating your command and the ">" prompt is intentional or part of my issue. If either of those are, is there a way to exclude those?

I don't mind dipping in to the code if required, but I would appreciate some pointers.

**Comment by JiFish** [comment]
Other options I have looked at use [Dumb Frotz](https://github.com/DavidGriffith/frotz/blob/master/DUMB) to ease issues with getting the output from frotz. I wonder if that is an option here?

**Comment by aeolingamenfel** [comment]
Hm, dumb frotz might be exactly what I was after, as parsing the output of Frotz directly is a pain. I'll look into patching that in! Thanks for the info!

**Comment by JiFish** [comment]
Glad it was helpful.

**Comment by JiFish** [comment]
With two small changes 826aee283bde9d0858be7966beb6c27491fe257e I was able to get it to use dfrotz and solve my formatting issue.

It might be possible to do something smarter with the output, but this works for me.

![dfrotz example](https://cloud.githubusercontent.com/assets/1314002/23088377/c8a1ef36-f573-11e6-9f44-311997d079ff.jpg)

**Comment by aeolingamenfel** [comment]
Sweet! I'll definitely patch that in. I wanna do a bit more cleaning of it though. Probably don't need the `>`, and can probably parse out the score and moves into something a little nicer. 

Thanks so much for your help with this!

**Comment by JiFish** [comment]
Thanks you for adding this.
